# Generated by Django 3.0.8 on 2020-07-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Out For Delivery'), (3, 'Delivered')], null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'Indoor'), (2, 'Out Door')], null=True),
        ),
    ]
