# Generated by Django 3.0.8 on 2020-07-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200714_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Out For Delivery'), (3, 'Delivered')], default=1, null=True),
        ),
    ]
