# Generated by Django 3.0.8 on 2020-07-14 16:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200714_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
